name: Terraform Format and Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Run terraform init
        run: terraform init

      - name: Run terraform fmt
        run: terraform fmt -recursive

      - name: Run terraform validate
        run: terraform validate

