name: Terraform Format and Validate

on:
  push:
    branches:
      - A03/workflow
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Run terraform fmt
        run: terraform fmt -recursive

      - name: Run terraform validate
<<<<<<< HEAD
        run: terraform validate
=======
        run: terraform validate
>>>>>>> 8ac044097328d219df8b09edac208ced68a2b603
